services:
  organizador:
    image: davtechw/mail_noty_telegram:latest
    container_name: organizador
    volumes:
      - ./sender_groups.json:/app/sender_groups.json:ro
      - ./.env:/app/.env:ro
    read_only: true
    tmpfs:
      - /tmp
    user: '2001:2001'
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    stop_signal: SIGINT
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    networks:
      - organizador_net

networks:
  organizador_net:
    driver: bridge
